# Generated by Django 3.0.3 on 2021-11-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('image_name', models.IntegerField()),
                ('description', models.TextField()),
                ('microscopy', models.CharField(max_length=60)),
                ('cell_type', models.CharField(max_length=60)),
                ('component', models.CharField(max_length=60)),
                ('doi', models.CharField(max_length=60)),
                ('organism', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('mailAddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('score', models.IntegerField(null=True)),
                ('gameActive', models.IntegerField(null=True)),
            ],
        ),
    ]
