# Generated by Django 3.0.3 on 2021-11-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('answer', models.CharField(max_length=60)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField()),
                ('quest', models.CharField(max_length=60)),
                ('quest_type', models.CharField(max_length=60)),
                ('quest_image_field', models.CharField(max_length=60)),
                ('quest_point', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('n_answer', models.IntegerField()),
                ('n_image', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='images',
            old_name='cell_type',
            new_name='img_cell_type',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='component',
            new_name='img_component',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='description',
            new_name='img_description',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='doi',
            new_name='img_doi',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_id',
            new_name='img_id',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='microscopy',
            new_name='img_mode',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image_name',
            new_name='img_name',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='organism',
            new_name='img_organism',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='url',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gameActive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mailAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
