# Generated by Django 3.0.3 on 2021-11-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0004_auto_20211107_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img_id',
        ),
    ]
