# Generated by Django 3.0.3 on 2021-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0006_images_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_id',
            field=models.IntegerField(),
        ),
    ]
