# Generated by Django 3.0.3 on 2021-11-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0010_auto_20211107_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img_id',
        ),
    ]
