# Generated by Django 3.0.3 on 2021-11-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0011_remove_images_img_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='img_url',
        ),
    ]
