# Generated by Django 3.0.3 on 2021-11-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0012_remove_images_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_id',
        ),
    ]
