# Generated by Django 3.0.3 on 2021-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0013_remove_question_q_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.CharField(max_length=120)),
                ('good_answer_id', models.IntegerField()),
            ],
        ),
    ]
