# Generated by Django 3.0.3 on 2021-11-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0014_answeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerUser',
        ),
    ]
