# Generated by Django 3.0.3 on 2021-11-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz_project_app', '0015_delete_answeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='n_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='n_image',
        ),
    ]
